/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef save_CONSTANTS_H
#define save_CONSTANTS_H

#include "save_types.h"

namespace save_service {

class saveConstants {
 public:
  saveConstants();

};

extern const saveConstants g_save_constants;

} // namespace

#endif
