/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "save_constants.h"

namespace save_service {

const saveConstants g_save_constants;

saveConstants::saveConstants() {
}

} // namespace

